### ISSUE TITLE
Random Segmentation Fault in the SDK on first S3 request

### ISSUE THREAD

**Issue by bu2** [awslabs/aws-sdk-cpp#16] opened 2015-09-27 15:37 UTC
Hi,

I am working on OS X Yosemite (10.10.5) with Xcode 7 and corresponding Clang/LLDB on a Mac Book Pro 13" of early 2015 (with force touch).

I made a simple program which:
- create a S3Client
- list objects from a specified S3 bucket
- download one file from the bucket

And I get a "random" segmentation fault on the first S3 request (ListObjects). By random, I mean that it happens some time but other time, my program runs without problem. In fact, I realised that most of the time it happens right after computer startup (but I do not understand why...).

From the LLDB backtrace, I can say:
- the EXC_BAD_ACCESS happens in a basic_string related operation
- it might be related to AWS credentials lookup (I am not specifying my credentials, the SDK find those automatically from ~/.aws/credentials)

I will provide more details in following messages.

Regards,

Bruno Le Hyaric.

**Comment by bu2** [comment] 2015-09-27 15:47
Here is a screenshot of my LLDB output (sorry but Github refuses my text files X-| )

<img width="1440" alt="screen shot 2015-09-27 at 17 39 06" src="https://cloud.githubusercontent.com/assets/227457/10123633/b7cba97a-653e-11e5-8a9b-81d878356078.png">

I would be glad to give the source of my program and a core dump on a secure channel, ex: email.
(how can we generate core dumps on the last OS X? I looked everywhere but was not able to get a dump...)

As far as I looked, it really seems to me that the segfault is in the SDK and may not be specific to my program. So I need some help to pinpoint the origin of the problem :-)

Regards,

Bruno Le Hyaric.

**Comment by JonathanHenson** [comment] 2015-09-27 15:54
By chance, are you using a std::string anywhere, but compiling with the
flag -DAWS_CUSTOM_MEMORY_MANAGEMENT?

It looks like it's segfaulting when a string goes out of scope on a
std::string. Instead use an Aws::String.

For sanity check, run the s3 integration tests  and make sure they  don't
segfault.

**Comment by bu2** [comment] 2015-09-27 16:11
I am using the flag -DAWS_CUSTOM_MEMORY_MANAGEMENT? and here is my code which make the ListObjects request:

```
static const char * const g_allocationTag = "beta";

...
...

Aws::UniquePtr<Aws::S3::Model::ListObjectsOutcome>
list_objects_from_bucket( const Aws::UniquePtr<Aws::S3::S3Client>& s3client,
			  const char * const bucket_name ) {
  auto request = Aws::S3::Model::ListObjectsRequest();
  request.SetBucket(bucket_name);
  return Aws::MakeUnique<Aws::S3::Model::ListObjectsOutcome>( g_allocationTag,
							      s3client->ListObjects(request) );
}
```

I am not using std::string but some old school c-string (char*)... could they be automatically boxed into std::string ?

And I am sorry to tell you that the S3 integration tests trigger the segfault too:

```
$ ./runS3IntegrationTests 
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from BucketAndObjectOperationTest
[ RUN      ] BucketAndObjectOperationTest.TestBucketCreationAndListing
Segmentation fault: 11
```

I am at your disposal if you need any more information. By the way, thanks for the quick answer !

Regards,

Bruno Le Hyaric.

**Comment by JonathanHenson** [comment] 2015-09-27 16:14
Can you checkout the revision prior to my push a few days ago, and retry?
We had to fix a bug in the generator and I'm curious if we broke the xml
parser in the meantime.

**Comment by JonathanHenson** [comment] 2015-09-27 16:21
Also you are passing a moved stack value to a unique ptr. That is going to
cause a segfault right there. The return value of listObjects will be
deallocated in the next line and the unique_ptr will be invalid.

**Comment by bu2** [comment] 2015-09-27 16:28
Ok,

I will check previous revision and keep you updated.

**Comment by bu2** [comment] 2015-09-27 16:37
I am not sure to understand your point regarding my unique_ptr.

From what I have seen in the SDK code, aws-sdk-cpp/aws-cpp-sdk-core/include/aws/core/utils/memory/AWSMemory.h, line 184:

```
template<typename T, typename ...ArgTypes>
UniquePtr<T> MakeUnique(const char* allocationTag, ArgTypes&&... args)
{
    return UniquePtr<T>(Aws::New<T>(allocationTag, std::forward<ArgTypes>(args)...));
}
```

Aws::MakeUnique() uses Aws::New so my returned object should be in the free store... right ?

**Comment by bu2** [comment] 2015-09-27 16:39
And as I said previously the segfault happens randomly... I could run the S3 integration tests just after waiting few minutes:

```
$ ./runS3IntegrationTests 
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from BucketAndObjectOperationTest
[ RUN      ] BucketAndObjectOperationTest.TestBucketCreationAndListing
[       OK ] BucketAndObjectOperationTest.TestBucketCreationAndListing (3980 ms)
[ RUN      ] BucketAndObjectOperationTest.TestBucketLocation
[       OK ] BucketAndObjectOperationTest.TestBucketLocation (3691 ms)
[ RUN      ] BucketAndObjectOperationTest.TestObjectOperations
[       OK ] BucketAndObjectOperationTest.TestObjectOperations (1979 ms)
[ RUN      ] BucketAndObjectOperationTest.TestObjectOperationsWithPresignedUrls
[       OK ] BucketAndObjectOperationTest.TestObjectOperationsWithPresignedUrls (1932 ms)
[ RUN      ] BucketAndObjectOperationTest.TestMultiPartObjectOperations

/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:162: Failure
Value of: outcome.IsSuccess()
  Actual: false
Expected: true
/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:162: Failure
Value of: outcome.IsSuccess()
  Actual: false
Expected: true
/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:576: Failure
Value of: completeMultipartUploadOutcome.IsSuccess()
  Actual: false
Expected: true
[  FAILED  ] BucketAndObjectOperationTest.TestMultiPartObjectOperations (357909 ms)
[ RUN      ] BucketAndObjectOperationTest.TestThatErrorsParse
[       OK ] BucketAndObjectOperationTest.TestThatErrorsParse (1820 ms)
[----------] 6 tests from BucketAndObjectOperationTest (371311 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (374724 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BucketAndObjectOperationTest.TestMultiPartObjectOperations

 1 FAILED TEST
```

**Comment by JonathanHenson** [comment] 2015-09-27 16:43
Why not just return the value of listObjects directly and change the return
type of the function to ListObjectsOutcome, and see what happens. Don't
reseat it into a smart pointer or anything like that. Let's see if the
segfault goes away then.

And as I said previously the segfault happens randomly... I could run the
S3 integration tests just after waiting few minutes:

$ ./runS3IntegrationTests
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from BucketAndObjectOperationTest
[ RUN      ] BucketAndObjectOperationTest.TestBucketCreationAndListing
[       OK ] BucketAndObjectOperationTest.TestBucketCreationAndListing (3980 ms)
[ RUN      ] BucketAndObjectOperationTest.TestBucketLocation
[       OK ] BucketAndObjectOperationTest.TestBucketLocation (3691 ms)
[ RUN      ] BucketAndObjectOperationTest.TestObjectOperations
[       OK ] BucketAndObjectOperationTest.TestObjectOperations (1979 ms)
[ RUN      ] BucketAndObjectOperationTest.TestObjectOperationsWithPresignedUrls
[       OK ] BucketAndObjectOperationTest.TestObjectOperationsWithPresignedUrls
(1932 ms)
[ RUN      ] BucketAndObjectOperationTest.TestMultiPartObjectOperations

/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:162:
Failure
Value of: outcome.IsSuccess()
  Actual: false
Expected: true
/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:162:
Failure
Value of: outcome.IsSuccess()
  Actual: false
Expected: true
/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/BucketAndObjectOperationTest.cpp:576:
Failure
Value of: completeMultipartUploadOutcome.IsSuccess()
  Actual: false
Expected: true
[  FAILED  ] BucketAndObjectOperationTest.TestMultiPartObjectOperations
(357909 ms)
[ RUN      ] BucketAndObjectOperationTest.TestThatErrorsParse
[       OK ] BucketAndObjectOperationTest.TestThatErrorsParse (1820 ms)
[----------] 6 tests from BucketAndObjectOperationTest (371311 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (374724 ms total)
[  PASSED  ] 5 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] BucketAndObjectOperationTest.TestMultiPartObjectOperations

 1 FAILED TEST

—
Reply to this email directly or view it on GitHub
<https://github.com/awslabs/aws-sdk-cpp/issues/16#issuecomment-143575758>.

**Comment by bu2** [comment] 2015-09-27 16:54
Ok,

I will try later (this evening or tomorrow) with the previous SDK revision and without smart pointers and keep you updated.

Thanks for your help!

**Comment by JonathanHenson** [comment] 2015-09-27 17:01
Just try without the smart pointers first. I don't think that's valid c++
the way you are using it and am almost certain that is a segfault.

**Comment by bu2** [comment] 2015-09-27 17:27
The problem occurs with previous revision too.
(commit: 20b67897d5a3079a89b01511cd520cb69de4412e)

**Comment by bu2** [comment] 2015-09-27 17:37
And the problem still occurs when removing smart pointers... :(

I succeeded to get a core dump if necessary.

Regards.

**Comment by bu2** [comment] 2015-09-27 17:38
Tomorrow,

I will try to provide you a minimal case which reproduce the problem.

Regards.

**Comment by JonathanHenson** [comment] 2015-09-27 17:39
Do you have this code in github or something. I'll debug it for you and see
where the problem is.

**Comment by bu2** [comment] 2015-09-27 18:15
Here is a minimal testcase which reproduces the random segfault: https://gist.github.com/bu2/5a584d459bd7b43d25fc

I compile manually like this:
```
$ clang++ -O0 -g -std=c++11 -Wall -pedantic  -Wno-unused-private-field -Wno-comment -DAWS_CUSTOM_MEMORY_MANAGEMENT -Iaws-sdk-cpp/aws-cpp-sdk-core/include -Iaws-sdk-cpp/aws-cpp-sdk-s3/include -Laws-sdk-cpp/build/aws-cpp-sdk-core -Laws-sdk-cpp/build/aws-cpp-sdk-s3 -laws-cpp-sdk-core -laws-cpp-sdk-s3 segfault.cpp -o segfault
```

When I reboot my mac and launch the program, then, the segfault happens... if I wait few minutes the segfault disappears :-?

Tell me if you can reproduce on your side.

**Comment by JonathanHenson** [comment] 2015-09-28 03:34
Ok.... I think this has nothing to do with S3, the segfault is in ProfileConfigFileCredentialsProvider. 

I just ran with my Mac, same version but from command line with clang and everything works. Investigating further.

**Comment by JonathanHenson** [comment] 2015-09-28 03:47
What I am seeing should not be possible. According to the stacktrace AWSCredentials is being initialized with null strings (which isn't possible according to the code path). There may be something funny is going on with the std lib for your C++ version and some funny static initialization stuff. Could you upload the log file that was generated by the program. Also, can you show a redacted credentials file?

**Comment by JonathanHenson** [comment] 2015-09-28 03:48
also, just a check. Can you post the output of git log?

**Comment by bu2** [comment] 2015-09-28 08:19
Here is the output of `$ git log` for the sdk:
```
commit e8c3478b5943ff1d8ef2be636814f425fc3b6956
Author: Henson <henso@amazon.com>
Date:   Tue Sep 22 16:39:59 2015 -0700

    Fixed XML deserialization. Fixes for EC2 (SDK coming soon).

commit 20b67897d5a3079a89b01511cd520cb69de4412e
Author: Henson <henso@amazon.com>
Date:   Tue Sep 8 18:03:45 2015 -0700

    Linux build fixes, updates for VS 2015.

commit 3eed2f2ec10a906b90a46d9755ec5de2989bc784
Author: Henson <henso@amazon.com>
Date:   Fri Sep 4 11:33:28 2015 -0700

    Finally fixed the mess caused by case-insensitive file systems.

...
...
```

I reverted back to the last revision and the testcase segfault.cpp still reproduce the problem.

**Comment by bu2** [comment] 2015-09-28 22:47
Hi Jonathan,

Sorry for the late answer, I did not see your previous questions...

Here is the log (after segfault):
```
[TRACE] 2015-09-29 00:32:50 FileSystemUtils [0x7fff7388c300] Checking HOME for the home directory.
[DEBUG] 2015-09-29 00:32:50 FileSystemUtils [0x7fff7388c300] Environment value for variable HOME is /Users/bu2
[INFO] 2015-09-29 00:32:50 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Setting provider to read credentials from /Users/bu2/.aws/credentials, for use with profile default.
[INFO] 2015-09-29 00:32:50 InstanceProfileCredentialsProvider [0x7fff7388c300] Creating Instance with default EC2MetadataClient and refresh rate 900000.
[INFO] 2015-09-29 00:32:50 EC2MetadataClient [0x7fff7388c300] Creating HttpClient with max connections 2 and scheme http
[INFO] 2015-09-29 00:32:50 CurlHandleContainer [0x7fff7388c300] Intializing CurlHandleContainer with size 2.
[INFO] 2015-09-29 00:32:50 CurlHandleContainer [0x7fff7388c300] Initializing Curl library
[INFO] 2015-09-29 00:32:50 CurlHandleContainer [0x7fff7388c300] Intializing CurlHandleContainer with size 25.
[TRACE] 2015-09-29 00:32:50 AWSClient [0x7fff7388c300] No content body, removing content-type and content-length headers
```

Here is what my ~/.aws/credentials looks like:
```
[default]
aws_access_key_id = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

And my ~/.aws/config (if necessary):
```
[default]
region = eu-west-1
```

And few more details regarding my environment:
```
# Up-to-date Apple official Clang
$ which clang++
/usr/bin/clang++

$ clang++ --version
Apple LLVM version 7.0.0 (clang-700.0.72)
Target: x86_64-apple-darwin14.5.0
Thread model: posix

# shared libraries in use
$ otool -L segfault
segfault:
	/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/build/aws-cpp-sdk-core/libaws-cpp-sdk-core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/Users/bu2/lab/aws/billing/beta/aws-sdk-cpp/build/aws-cpp-sdk-s3/libaws-cpp-sdk-s3.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
```

Were you able to reproduce the problem on your side ?

Regards.

**Comment by bu2** [comment] 2015-09-28 23:00
And after waiting few minutes, the program 'segfault.cpp' run just fine producing following log:

```
[TRACE] 2015-09-29 00:51:11 FileSystemUtils [0x7fff7388c300] Checking HOME for the home directory.
[DEBUG] 2015-09-29 00:51:11 FileSystemUtils [0x7fff7388c300] Environment value for variable HOME is /Users/bu2
[INFO] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Setting provider to read credentials from /Users/bu2/.aws/credentials, for use with profile default.
[INFO] 2015-09-29 00:51:11 InstanceProfileCredentialsProvider [0x7fff7388c300] Creating Instance with default EC2MetadataClient and refresh rate 900000.
[INFO] 2015-09-29 00:51:11 EC2MetadataClient [0x7fff7388c300] Creating HttpClient with max connections 2 and scheme http
[INFO] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Intializing CurlHandleContainer with size 2.
[INFO] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Initializing Curl library
[INFO] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Intializing CurlHandleContainer with size 25.
[TRACE] 2015-09-29 00:51:11 AWSClient [0x7fff7388c300] No content body, removing content-type and content-length headers
[DEBUG] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Refreshing credentials.
[DEBUG] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Found profile default.
[TRACE] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Found property aws_access_key_idfor profile default
[TRACE] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Found property aws_secret_access_keyfor profile default
[INFO] 2015-09-29 00:51:11 ProfileConfigFileAWSCredentialsProvider [0x7fff7388c300] Optional session token for profile not found.
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Calculated sha256 e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 for payload.
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Canonical Header String: host:s3-eu-west-1.amazonaws.com
user-agent:aws-sdk-cpp/0.9-460-g9f17f3c Darwin/14.5.0 x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150928T225111Z

[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Signed Headers value:host;user-agent;x-amz-content-sha256;x-amz-date
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Canonical Request String: GET
/adaptive-biiling-bucket

host:s3-eu-west-1.amazonaws.com
user-agent:aws-sdk-cpp/0.9-460-g9f17f3c Darwin/14.5.0 x86_64
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20150928T225111Z

host;user-agent;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Final String to sign: AWS4-HMAC-SHA256
20150928T225111Z
20150928/eu-west-1/s3/aws4_request
1eb3b1a5118bef7b72b01ee14b9c097fe98d1ac74c1e9eb88094347f910740da
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Final computed signing hash: 3b6c3d42ef23d2dddcf2755f42c5b29bceddcd4916631b12ab01a1f250eb1a8d
[DEBUG] 2015-09-29 00:51:11 AWSAuthV4Signer [0x7fff7388c300] Signing request with: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20150928/eu-west-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=3b6c3d42ef23d2dddcf2755f42c5b29bceddcd4916631b12ab01a1f250eb1a8d
[DEBUG] 2015-09-29 00:51:11 AWSClient [0x7fff7388c300] Request Successfully signed
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] Making request to https://s3-eu-west-1.amazonaws.com/adaptive-biiling-bucket
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] Including headers:
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXXXXXXX/20150928/eu-west-1/s3/aws4_request, SignedHeaders=host;user-agent;x-amz-content-sha256;x-amz-date, Signature=3b6c3d42ef23d2dddcf2755f42c5b29bceddcd4916631b12ab01a1f250eb1a8d
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] host: s3-eu-west-1.amazonaws.com
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] user-agent: aws-sdk-cpp/0.9-460-g9f17f3c Darwin/14.5.0 x86_64
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
[TRACE] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] x-amz-date: 20150928T225111Z
[DEBUG] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Attempting to acquire curl connection.
[DEBUG] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] No current connections available in pool. Attempting to create new connections.
[DEBUG] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] attempting to grow pool size by 2.
[INFO] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Pool successfully grown by 2
[DEBUG] 2015-09-29 00:51:11 CurlHandleContainer [0x7fff7388c300] Returning connection handle 0x7fb3dc010a00.
[DEBUG] 2015-09-29 00:51:11 CurlHttpClient [0x7fff7388c300] Obtained connection handle 0x7fb3dc010a00.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] HTTP/1.1 200 OK

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] x-amz-id-2: 0jgAcrMMq8oZl428oo6lsoVaavmrRto+WNiCuEzvs5ZsvBYITLhXdyJs///AL3CGJstKllMI2kM=

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] x-amz-request-id: CCA20C70120C402E

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Date: Mon, 28 Sep 2015 22:51:13 GMT

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] x-amz-bucket-region: eu-west-1

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Content-Type: application/xml

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Transfer-Encoding: chunked

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Server: AmazonS3

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 

[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 8192 bytes written to response.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 8178 bytes written to response.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 14 bytes written to response.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 711 bytes written to response.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 7481 bytes written to response.
[TRACE] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] 2091 bytes written to response.
[DEBUG] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Returned http response code 200.
[DEBUG] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Returned content type application/xml.
[DEBUG] 2015-09-29 00:51:12 CurlHttpClient [0x7fff7388c300] Releasing curl handle 0x7fb3dc010a00.
[DEBUG] 2015-09-29 00:51:12 CurlHandleContainer [0x7fff7388c300] Releasing curl handle 0x7fb3dc010a00.
[DEBUG] 2015-09-29 00:51:12 CurlHandleContainer [0x7fff7388c300] Notifying waiting threads.
[DEBUG] 2015-09-29 00:51:12 AWSClient [0x7fff7388c300] Request returned successful response.
[TRACE] 2015-09-29 00:51:12 AWSClient [0x7fff7388c300] Request was either successful, or we are now out of retries.
```

**Comment by JonathanHenson** [comment] 2015-09-28 23:21
I'm running an identical build setup. I can't reproduce the problem both your code and the integration tests run fine.

Let me reboot my machine and run it immediately after boot and see what happens.

**Comment by JonathanHenson** [comment] 2015-09-28 23:28
just got it to happen immediately after startup. Investigating now.

**Comment by JonathanHenson** [comment] 2015-09-28 23:55
This has got to be a bug in the OSX c++ runtime, it started working after 10 minutes.

**Comment by bu2** [comment] 2015-09-28 23:57
Good.

Tell me if I can help to investigate.

Regards.

**Comment by JonathanHenson** [comment] 2015-09-29 00:19
I think it's probably related to this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=63610

Looking further.

**Comment by bu2** [comment] 2015-09-29 13:16
Ok, interesting.

Do you have an idea of why the same compiled binary happens to work once we wait for some (random) time ?

Thanks for your time.

**Comment by JonathanHenson** [comment] 2015-09-29 14:21
Yep.... same exact binary.

**Comment by JonathanHenson** [comment] 2015-09-29 14:56
If I had to guess, we are linking to different version of libc++ from different binaries and they are incompatible. I'm going to test that theory today.

**Comment by bu2** [comment] 2015-09-29 16:47
I found another (weird) clue.

I boot the mac with all network devices down (wifi / ethernet off).
I use this shell script to run continuously the program "segfault" just after booting the mac:
```
$ cat debug_segfault.sh 
#!/bin/bash

false || while [ $? != 0 ]
do
    date "+%Y-%m-%d %H:%M:%S"
    uptime 
    time ./segfault
done
```

And the program start to run correctly around 15 minutes after boot (it fails to request S3 because the network is down but the execution ends gracefully without segfault). I tried 3 times with the same result and timing...
So I will monitor what happens under the system's hood, at 15 minutes after boot, to look for more clues (in system logs, shared libraries in use...).

I would appreciate if your mac have 15 minutes of availability in order to run the same (silly) experiment on your side...

I keep you posted.

**Comment by JonathanHenson** [comment] 2015-10-01 16:48
your test program had the same effect on my machine. Have you had any luck finding the cause?

**Comment by bu2** [comment] 2015-10-01 18:30
No, unfortunately...

I just know the problem still happen on OS X El Capitan :-(

Bruno.

**Comment by JonathanHenson** [comment] 2015-10-01 19:06
what happens if you set --main-stacksize=   to something really large when you launch the program?

**Comment by bu2** [comment] 2015-10-02 09:42
Do you mean like:

$ ./segfault --main-stacksize=1000000000

?

**Comment by JonathanHenson** [comment] 2015-10-02 14:19
Yep

**Comment by JonathanHenson** [comment] 2015-10-02 16:45
I found the problem! Or at least the immediate cause of the segfault.

I added 
assert(m_credentials != nullptr) 

which should be impossible  to AWSCredentialsProvider.cpp line 197.

at startup, the assertion fails.

**Comment by JonathanHenson** [comment] 2015-10-02 16:55
ok..... found it
high_resolution_clock::now() 
does not work, something turns it on 15 minutes into boot and every thing works.

**Comment by JonathanHenson** [comment] 2015-10-02 17:15
One more thing. high_resolution_clock::now().time_since_epoch() returns the time since boot, which is why everything started working after 15 minutes.

**Comment by JonathanHenson** [comment] 2015-10-02 17:32
Try changing line 69 of AWSCredentialsProvider.cpp to 

milliseconds now = duration_cast<milliseconds>(system_clock::now().time_since_epoch());

**Comment by JonathanHenson** [comment] 2015-10-02 17:42
Confirmed that fixes the issue. I'm going to push the change through our pipeline. Thank you for pointing this out, this would have slipped out into the wild and we would likely not have found it until it was too late. 

I'm sorry you had trouble, but grateful for your help. Close the issue once, you've confirmed.

If you'd like, make the change I mentioned above and everything should work. Then when we push, you can just merge our changes.

**Comment by bu2** [comment] 2015-10-02 18:55
Wow ! Great job John !

I am glad we were not wasting our time on some unworkable OS X bug :-)

I am confident with your fix but I can not build the SDK anymore since I switch to El Capitan. It seems Apple change the way they package C/C++ include headers... 

So I am closing this issue, and create a new one for El Capitan.

Thank you for your time and the fix !

Bruno.

**Closed** 2015-10-02 18:55 UTC

**Comment by bu2** [comment] 2015-10-02 22:25
I confirm that the fix works fine!

Thank you Jonathan.
