### ISSUE TITLE
uploading file to s3 using aws-sdk-cpp-transfer do nothing

### ISSUE THREAD

**Issue by chemidy** [awslabs/aws-sdk-cpp#96] opened 2016-02-03 15:33 UTC
I try to upload a file to s3 with transfer, but nothing happens and trace log is empty.
Any Idea ?
`

Aws::Utils::Logging::InitializeAWSLogging(Aws::MakeShared<Aws::Utils::Logging::DefaultLogSystem>("Internal_Logger", Aws::Utils::Logging::LogLevel::Trace, "aws_sdk_"));

    ClientConfiguration config;
    config.scheme = Scheme::HTTPS;
    config.connectTimeoutMs = 30000;
    config.requestTimeoutMs = 30000;

    TransferClientConfiguration transferConfig;
    transferConfig.m_uploadBufferCount = 20;

    std::shared_ptr<S3Client> m_s3Client = Aws::MakeShared<S3Client>("Upload", config);
    std::shared_ptr<TransferClient> m_transferClient = Aws::MakeShared<TransferClient>("Upload", m_s3Client, transferConfig);

    std::shared_ptr<UploadFileRequest> requestPtr = m_transferClient->UploadFile("myFile.zip", "MyLiTTleBucket", "myFile.zip", "application/zip", false, false);
    

    Aws::Utils::Logging::ShutdownAWSLogging();`

`
[TRACE] 2016-02-03 16:31:13 FileSystemUtils [139892860249920] Checking HOME for the home directory.

[DEBUG] 2016-02-03 16:31:13 FileSystemUtils [139892860249920] Environment value for variable HOME is /home/chemidy

[DEBUG] 2016-02-03 16:31:13 FileSystemUtils [139892860249920] Home directory is missing the final / appending one to normalize
[DEBUG] 2016-02-03 16:31:13 FileSystemUtils [139892860249920] Final Home Directory is /home/chemidy/

[INFO] 2016-02-03 16:31:13 ProfileConfigFileAWSCredentialsProvider [139892860249920] Setting provider to read credentials from /home/chemidy//.aws/credentials, for use with profile default.

[INFO] 2016-02-03 16:31:13 InstanceProfileCredentialsProvider [139892860249920] Creating Instance with default EC2MetadataClient and refresh rate 900000.

[INFO] 2016-02-03 16:31:13 EC2MetadataClient [139892860249920] Creating HttpClient with max connections 2 and scheme http

[INFO] 2016-02-03 16:31:13 CurlHandleContainer [139892860249920] Intializing CurlHandleContainer with size 2

[INFO] 2016-02-03 16:31:13 CurlHandleContainer [139892860249920] Initializing Curl library

[INFO] 2016-02-03 16:31:13 CurlHandleContainer [139892860249920] Intializing CurlHandleContainer with size 25
`

**Comment by kahkeng** [comment] 2016-02-04 21:18
I think this might be because the UploadFile call will trigger the upload to happen asynchronously. So you'll need to wait for the upload to finish before your program quits.

You could do something like this to wait for the request to finish (either successfully or with an error).
```
while (!requestPtr->IsDone()) {
    std::this_thread::sleep_for(std::chrono::seconds(1));
}
```
You can also look at `WaitForUploadAndUpdate` in aws-cpp-sdk-transfer-tests/TransferTests.cpp for more ways to check on the status of the upload.

**Comment by JonathanHenson** [comment] 2016-02-04 22:17
Emulating synchronous behavior is probably not what you want in a real environment (unless the code above is your production code and isn't doing anything more complex). 

The problem is that this pointer being returned by UploadFile is getting cleaned up when you exit the stackframe, which is calling the destructor of UploadFileRequest. You need to take a handle to that pointer outside of the scope of this method and then use the callbacks to handle the upload finishing.

If all you need to do is what you posted above, then kahkeng's advice is best.

**Comment by JonathanHenson** [comment] 2016-02-18 01:50
closing. Please repoen if issue persists.

**Closed by JonathanHenson** 2016-02-18 01:50 UTC
